---
- name: ensure install nvim (neovim)
  dnf:
    name: neovim
    state: present
  tags:
    - dotfiles
    - nvim

- name: check if nvim autoload directory exists
  stat:
    path: "{{ home_path }}/.local/share/nvim/site/autoload/"
  become: false
  register: autoload
  tags:
    - dotfiles
    - nvim


- name: check if nvim config directory exists
  stat:
    path: "{{ home_path }}/.config/nvim"
  become: false
  register: nvim
  tags:
    - dotfiles
    - nvim

- name: Deploy ultimate vim config
  become: no
  git:
    dest: "{{ home_path }}/.vim_runtime"
    repo: https://github.com/amix/vimrc
    clone: yes
    update: yes
    recursive: no
    depth: 1
  register: repo_clone
  failed_when:
    - repo_clone.failed
    - not 'Local modifications exist in the destination:' in repo_clone.msg

- name: Install ultimate vim config
  become: no
  command: sh "{{ home_path }}/.vim_runtime/install_awesome_vimrc.sh"
