---
- name: add/enable rpmfusion repositories [free, nonfree]
  dnf:
    disable_gpg_check: true
    name: [ "{{ repo_rpmfusion | join(',') }}" ]
    state: present
  tags:
    - packages

#- name: add/enable iridium repository
  #command: dnf config-manager --add-repo "{{ repo_iridium }}"
  #tags:
    #- packages

#- name: add osquery repository gpg key
  #rpm_key:
    #state: present
    #key: "{{ rpm_gpp_key_osquery }}"
  #tags:
    #- packages

#- name: add/enable osquery repository
  #command: dnf config-manager --add-repo "{{ repo_osquery }}"
  #tags:
    #- packages

- name: add/enable kopia repository
  copy:
    src: "etc/yum.repos.d/kopia.repo"
    dest: "/etc/yum.repos.d/kopia.repo"
    owner: root
    group: root
    mode: 0644
  tags:
    - packages

- name: add/enable anydesk repository
  become: yes
  yum_repository:
    name: anydesk
    description: Anydesk
    baseurl: http://rpm.anydesk.com/fedora/$basearch/
    enabled: yes
    gpgkey: https://keys.anydesk.com/repos/RPM-GPG-KEY
    gpgcheck: yes





# Install VSCode

- name: Add Microsoft rpm key
  become: yes
  rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add VS Code repository
  become: yes
  yum_repository:
    name: code
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: yes


- name: install packages
  dnf:
    name: "{{ packages }}"
    state: present
  tags:
    - packages

- name: Add the flathub flatpak repository remote to the user installation
  tags: flatpak
  become: no
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install Flatpack packages
  become: no
  community.general.flatpak:
    name: "{{ flatpaks }}"
    state: present
    method: user
  tags:
    - flatpak


#- name: install third party packages [keybase, zoom]
  #dnf:
    #disable_gpg_check: true
    #name: [ "{{ package_third_party | join(',') }}" ]
    #state: present
  #tags:
    ##- keybase
    #- packages
    ## - zoom


- name: autoremove unneeded packages installed as dependencies
  dnf:
    autoremove: true
    state: absent
  tags:
    - packages
